# start up
/run/initialize
#
# open an OpenGL viewer
/vis/open OGLI
#
# draw geometry
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector 1 0 0
/vis/viewer/set/viewpointThetaPhi 120 150
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 4 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawAuxPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsSize 4

/vis/viewer/set/hiddenMarker false
#
# draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# Make the "World" box invisible
/vis/geometry/set/visibility World 0 false
#
# draw axes
/vis/scene/add/axes
#
# Superimpose all of the events from a given run:
/vis/scene/endOfEventAction accumulate